version: '3.8'
services:
  mongo:
    container_name: mongo-flashcard
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - '27017:27017'
    networks:
      - flashcard-network

  app:
    container_name: flashcard-app
    image: flashcard-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - 'mongo'
    networks:
      - flashcard-network
    ports:
      - '3000:3000'
    environment:
      MONGO_PORT: 27017
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASSWORD: toor

networks:
  flashcard-network:
    driver: bridge
