name: Build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Use Cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build
