name: Pipeline Master
on:
  push:
    branches: ['master']

jobs:
  lint:
    uses: caionastu/flashcard-node/.github/workflows/lint.yml@master

  build:
    need: lint
    uses: caionastu/flashcard-node/.github/workflows/build.yml@master

  pipeline:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Send discord notification
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{secrets.DISCORD_WEBHOOK}}
          content: 'Test from githubActions'
