name: Pipeline Master
on:
  push:
    branches: ['master']

jobs:
  lint:
    uses: caionastu/flashcard-node/.github/workflows/lint.yml@master

  build:
    needs: lint
    uses: caionastu/flashcard-node/.github/workflows/build.yml@master

  test:
    needs: lint
    uses: caionastu/flashcard-node/.github/workflows/test.yml@master

  success-discord-notification:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      - name: Send discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: 'commit'
          description: 'Commit was successfully linted, tested and built.'

  failure-discord-notification:
    if: ${{ failure() }}
    needs: [lint, build, test]
    runs-on: ubuntu-latest

    steps:
      - name: Send discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK}}
          noprefix: true
          title: 'failure'
          description: ':rage: :rage: There is an error in commit. Please, fix the errors. :rage: :rage:'
          color: 0xff91a4
