name: Pipeline Master
on:
  push:
    branches: ['master']

jobs:
  pipeline:
    runs-on: ubuntu-latest

    call-workflow:
      uses: caionastu/flashcard-node/.github/workflows/lint.yml@master

    call-workflow:
      uses: caionastu/flashcard-node/.github/workflows/build.yml@master

    steps:
      - name: Send discord notification
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{secrets.DISCORD_WEBHOOK}}
          content: "Test from githubActions"
      
